-- Signal Desk seed data (VS-4). Run after schema.sql, in the Supabase SQL editor.
-- Everything here is synthetic: companies, contacts, acres and the prior-week
-- numbers are invented for the hackathon demo.

-- ---------------------------------------------------------------- settings
insert into public.settings (id, price_list, weekly_history) values (
  1,
  '{"Irrigation Scheduling":4.00,"Field-Work Planner":2.50,"Yield & Insurance Records":1.50,"setup":2500}',
  -- Four prior weeks per rep id, oldest first. Seeded, not computed.
  '{
    "1": {"pipeline":[42000,55000,61000,78000], "capture":[71,76,80,82], "hours":[1.3,1.7,2.0,2.3]},
    "2": {"pipeline":[18000,22000,20000,26000], "capture":[74,79,80,81], "hours":[0.7,0.7,1.0,1.0]},
    "3": {"pipeline":[35000,31000,40000,44000], "capture":[52,55,50,58], "hours":[1.0,1.3,1.3,1.7]},
    "4": {"pipeline":[40000,46000,43000,52000], "capture":[70,72,75,76], "hours":[1.3,1.3,1.7,2.0]},
    "5": {"pipeline":[30000,28000,34000,36000], "capture":[38,35,33,31], "hours":[1.0,1.0,1.3,1.3]},
    "6": {"pipeline":[22000,25000,24000,29000], "capture":[36,34,35,33], "hours":[0.7,1.0,1.0,1.0]}
  }'
);

-- ---------------------------------------------------------------- reps
-- Placeholder names are one UPDATE away, e.g.:
--   update public.reps set name = 'Jane Doe' where id = 2;
insert into public.reps (id, name, territory_name, counties, is_manager) values
  (1, 'Dana Whitfield', 'W. Kansas & Panhandles',
     array['Finney, KS','Kearny, KS','Grant, KS','Haskell, KS','Seward, KS','Texas, OK','Cimarron, OK','Deaf Smith, TX','Parmer, TX'], false),
  (2, 'Rep 2', 'Eastern Kansas',
     array['Douglas, KS','Franklin, KS','Shawnee, KS','Jefferson, KS','Osage, KS','Lyon, KS'], false),
  (3, 'Rep 3', 'Western Nebraska',
     array['Lincoln, NE','Dawson, NE','Keith, NE','Perkins, NE','Chase, NE'], false),
  (4, 'Rep 4', 'Eastern Nebraska',
     array['Saunders, NE','Butler, NE','Seward, NE','York, NE','Lancaster, NE','Dodge, NE'], false),
  (5, 'Rep 5', 'Central Oklahoma',
     array['Kingfisher, OK','Canadian, OK','Logan, OK','Grady, OK','Garfield, OK','Caddo, OK'], false),
  (6, 'Rep 6', 'Texas South Plains',
     array['Lubbock, TX','Hale, TX','Lamb, TX','Hockley, TX','Lynn, TX','Crosby, TX'], false),
  (7, 'Manager', 'Plains region', '{}', true);

-- ---------------------------------------------------------------- accounts
-- 50 accounts: 22 in Dana's territory. 8 prospects (own nothing), 4 own all three modules.
insert into public.accounts (name, contact_name, county, state, lat, lng, crops, acres, modules_owned, last_contact, rep_id) values
  -- Dana Whitfield (rep 1)
  ('Garden City Grain Co-op',        'Mark Reinholt',  'Finney',     'KS', 37.97, -100.87, array['Corn','Sorghum'],          4200, array['Field-Work Planner'], '2026-08-12', 1),
  ('Holcomb Family Farms',           'Jenny Holcomb',  'Finney',     'KS', 37.99, -101.00, array['Corn','Wheat'],            2800, array['Field-Work Planner'], '2026-07-28', 1),
  ('Plymell Ag Partners',            'Luis Arriaga',   'Finney',     'KS', 37.82, -100.72, array['Sorghum'],                 1900, array['Irrigation Scheduling'], '2026-06-30', 1),
  ('Pierceville Land LLC',           'Tom Brandt',     'Finney',     'KS', 37.87, -100.64, array['Wheat'],                   3100, array[]::text[], null, 1),
  ('Finney County Irrigation District','Carla Sosa',   'Finney',     'KS', 38.10, -100.80, array['Corn','Soybeans'],         6500, array['Irrigation Scheduling','Field-Work Planner','Yield & Insurance Records'], '2026-09-02', 1),
  ('Lakin Pivot Farms',              'Ray Doerksen',   'Kearny',     'KS', 37.94, -101.26, array['Corn'],                    3400, array['Yield & Insurance Records'], '2026-08-20', 1),
  ('Deerfield Sorghum Growers',      'Ana Pineda',     'Kearny',     'KS', 37.98, -101.13, array['Sorghum','Wheat'],         2200, array[]::text[], null, 1),
  ('Arkansas Valley Ditch Co.',      'Hal Price',      'Kearny',     'KS', 38.06, -101.40, array['Alfalfa','Corn'],          1600, array['Irrigation Scheduling'], '2026-05-14', 1),
  ('Ulysses Ag Cooperative',         'Beth Kerr',      'Grant',      'KS', 37.58, -101.36, array['Corn','Wheat','Sorghum'],  5200, array['Field-Work Planner','Yield & Insurance Records'], '2026-08-05', 1),
  ('Hickok Farms',                   'Dale Hickok',    'Grant',      'KS', 37.51, -101.24, array['Wheat'],                   1200, array['Irrigation Scheduling','Field-Work Planner','Yield & Insurance Records'], '2026-09-10', 1),
  ('Sublette Grain & Supply',        'Kurt Wagner',    'Haskell',    'KS', 37.48, -100.84, array['Corn','Soybeans'],         3800, array['Yield & Insurance Records'], '2026-07-15', 1),
  ('Satanta Family Ranch',           'Gloria Ruiz',    'Haskell',    'KS', 37.44, -100.99, array['Sorghum'],                  900, array[]::text[], null, 1),
  ('Liberal Plains Farms',           'Nick Ortega',    'Seward',     'KS', 37.08, -100.92, array['Corn','Wheat'],            2600, array['Field-Work Planner'], '2026-08-26', 1),
  ('Kismet Land & Cattle',           'Pat Leland',     'Seward',     'KS', 37.20, -100.70, array['Wheat','Sorghum'],         1700, array['Yield & Insurance Records'], '2026-04-22', 1),
  ('Guymon Irrigated Acres',         'Wes Carlile',    'Texas',      'OK', 36.68, -101.48, array['Corn'],                    4100, array['Field-Work Planner'], '2026-08-18', 1),
  ('Hooker Wheat Growers',           'Sara Lindley',   'Texas',      'OK', 36.86, -101.21, array['Wheat'],                   2400, array['Yield & Insurance Records'], '2026-07-09', 1),
  ('Goodwell Family Farms',          'Jim Stroud',     'Texas',      'OK', 36.60, -101.64, array['Sorghum','Wheat'],         1300, array['Irrigation Scheduling'], '2026-06-11', 1),
  ('Boise City Farms',               'Ella Maddox',    'Cimarron',   'OK', 36.73, -102.51, array['Wheat','Sorghum'],         2000, array[]::text[], null, 1),
  ('Hereford Feedgrain Co-op',       'Rick Alvarez',   'Deaf Smith', 'TX', 34.82, -102.40, array['Corn','Sorghum'],          5600, array['Irrigation Scheduling'], '2026-09-24', 1),
  ('Dawn Farms',                     'Megan Pruitt',   'Deaf Smith', 'TX', 34.91, -102.19, array['Corn','Wheat'],            2300, array['Field-Work Planner'], '2026-09-24', 1),
  ('Bootleg Corner Ag',              'Juan Tijerina',  'Deaf Smith', 'TX', 35.02, -102.88, array['Sorghum'],                 1400, array[]::text[], '2026-09-24', 1),
  ('Friona Grain Partners',          'Kelly Burch',    'Parmer',     'TX', 34.64, -102.72, array['Corn','Wheat'],            3000, array['Irrigation Scheduling','Field-Work Planner','Yield & Insurance Records'], '2026-08-29', 1),
  -- Rep 2, Eastern Kansas
  ('Baldwin Creek Farms',            'Amy Stroh',      'Douglas',    'KS', 38.78, -95.19, array['Soybeans','Corn'],          1100, array['Irrigation Scheduling'], '2026-09-24', 2),
  ('Kaw Valley Growers',             'Ben Fuller',     'Douglas',    'KS', 38.98, -95.35, array['Corn','Soybeans'],          2400, array[]::text[], '2026-09-24', 2),
  ('Ottawa Grain Co.',               'Cheryl Nguyen',  'Franklin',   'KS', 38.61, -95.27, array['Soybeans','Wheat'],         1800, array['Field-Work Planner'], '2026-08-01', 2),
  ('Topeka Bottoms Farms',           'Dan Marsh',      'Shawnee',    'KS', 39.08, -95.64, array['Corn'],                     1500, array['Irrigation Scheduling','Field-Work Planner'], '2026-07-19', 2),
  ('Emporia Ridge Ag',               'Faye Colby',     'Lyon',       'KS', 38.40, -96.18, array['Wheat','Soybeans'],         2000, array['Yield & Insurance Records'], '2026-06-24', 2),
  -- Rep 3, Western Nebraska
  ('North Platte Irrigators',        'Greg Olsen',     'Lincoln',    'NE', 41.12, -100.77, array['Corn','Soybeans'],         4800, array['Field-Work Planner'], '2026-09-25', 3),
  ('Lexington Grain Co-op',          'Hannah Buhr',    'Dawson',     'NE', 40.78, -99.74, array['Corn','Soybeans'],          5200, array['Irrigation Scheduling'], '2026-08-14', 3),
  ('Cozad Family Farms',             'Ivan Petersen',  'Dawson',     'NE', 40.86, -99.98, array['Corn'],                     1700, array[]::text[], null, 3),
  ('Ogallala Pivot Co.',             'Joan Haas',      'Keith',      'NE', 41.13, -101.72, array['Corn','Wheat'],            3300, array['Yield & Insurance Records'], '2026-09-24', 3),
  ('Grant Dryland Partners',         'Kyle Mertz',     'Perkins',    'NE', 40.84, -101.60, array['Wheat'],                   2600, array['Field-Work Planner'], '2026-07-30', 3),
  ('Imperial Ag Holdings',           'Lori Anders',    'Chase',      'NE', 40.52, -101.64, array['Corn','Soybeans'],         3900, array['Irrigation Scheduling','Field-Work Planner'], '2026-08-08', 3),
  -- Rep 4, Eastern Nebraska
  ('Wahoo Grain Growers',            'Mike Novak',     'Saunders',   'NE', 41.21, -96.62, array['Corn','Soybeans'],          2900, array['Irrigation Scheduling'], '2026-09-23', 4),
  ('Ashland Bottom Farms',           'Nora Kubik',     'Saunders',   'NE', 41.04, -96.37, array['Soybeans'],                 1400, array['Yield & Insurance Records'], '2026-07-02', 4),
  ('David City Ag',                  'Omar Haddad',    'Butler',     'NE', 41.25, -97.13, array['Corn'],                     2100, array['Irrigation Scheduling','Field-Work Planner','Yield & Insurance Records'], '2026-08-21', 4),
  ('York County Seed Farms',         'Paula Rystrom',  'York',       'NE', 40.87, -97.59, array['Corn','Soybeans'],          3600, array['Irrigation Scheduling'], '2026-09-23', 4),
  ('Waco Family Farms',              'Quinn Esch',     'York',       'NE', 40.90, -97.46, array['Corn','Wheat'],             1900, array[]::text[], '2026-09-23', 4),
  ('Fremont Valley Growers',         'Rosa Lind',      'Dodge',      'NE', 41.43, -96.50, array['Soybeans','Corn'],          2500, array['Field-Work Planner'], '2026-06-17', 4),
  -- Rep 5, Central Oklahoma
  ('Kingfisher Wheat Co-op',         'Sam Jantz',      'Kingfisher', 'OK', 35.86, -97.93, array['Wheat','Sorghum'],          4400, array['Field-Work Planner'], '2026-09-25', 5),
  ('Hennessey Farms',                'Tina Wolfe',     'Kingfisher', 'OK', 36.10, -97.90, array['Wheat'],                    1600, array['Yield & Insurance Records'], '2026-05-29', 5),
  ('El Reno Grain',                  'Ulises Mora',    'Canadian',   'OK', 35.53, -97.95, array['Wheat','Soybeans'],         2700, array['Yield & Insurance Records'], '2026-07-07', 5),
  ('Guthrie Ag Partners',            'Vera Holt',      'Logan',      'OK', 35.88, -97.42, array['Wheat','Corn'],             1800, array['Field-Work Planner','Yield & Insurance Records'], '2026-08-03', 5),
  ('Enid Plains Farms',              'Walt Schmidt',   'Garfield',   'OK', 36.40, -97.88, array['Wheat'],                    3500, array['Yield & Insurance Records'], '2026-06-26', 5),
  ('Anadarko Valley Farms',          'Xena Tsatoke',   'Caddo',      'OK', 35.07, -98.24, array['Cotton','Wheat'],           2300, array['Irrigation Scheduling'], '2026-08-11', 5),
  -- Rep 6, Texas South Plains
  ('Lubbock Cotton & Grain',         'Yolanda Reyes',  'Lubbock',    'TX', 33.58, -101.85, array['Cotton','Sorghum'],        5100, array['Field-Work Planner'], '2026-09-24', 6),
  ('Plainview Irrigated Farms',      'Zach Keller',    'Hale',       'TX', 34.18, -101.71, array['Corn','Cotton'],           3900, array['Yield & Insurance Records'], '2026-07-21', 6),
  ('Littlefield Growers',            'Aaron Bell',     'Lamb',       'TX', 33.92, -102.32, array['Cotton'],                  2800, array['Irrigation Scheduling'], '2026-06-15', 6),
  ('Levelland Sorghum Co.',          'Brenda Cho',     'Hockley',    'TX', 33.59, -102.38, array['Sorghum','Wheat'],         2200, array['Field-Work Planner'], '2026-08-27', 6),
  ('Tahoka Family Farms',            'Cody Harmon',    'Lynn',       'TX', 33.17, -101.80, array['Cotton','Wheat'],          1500, array['Irrigation Scheduling','Field-Work Planner'], '2026-05-20', 6);

-- ---------------------------------------------------------------- signals
insert into public.signals (week_of, county, state, lat, lng, type, severity, headline, detail, source, status, rep_id, drought_level) values
  -- Week of 2026-09-23 (this week), 11 signals
  ('2026-09-23', 'Finney', 'KS', 37.99, -100.74, 'drought', 'High',
   'Finney County, Kansas moved from D2 to D3 (extreme drought)',
   'Third consecutive week of decline. Irrigated corn and sorghum in the county are past silking; water allocation decisions are being made now.',
   'US Drought Monitor, released Sep 25 (seeded for the demo)', 'new', 1, 3),
  ('2026-09-23', 'Texas', 'OK', 36.75, -101.49, 'drought', 'Medium',
   'Texas County, Oklahoma moved from D1 to D2 (severe drought)',
   'Topsoil moisture is short across most of the county. Pivot operators are deciding how to split limited water between fall-planted wheat and remaining sorghum.',
   'US Drought Monitor, released Sep 25 (seeded for the demo)', 'new', 1, 2),
  ('2026-09-23', 'Deaf Smith', 'TX', 34.97, -102.60, 'heat', 'High',
   'Deaf Smith County, Texas: 4 days over 98 °F',
   'Four consecutive days above 98 °F while late-planted sorghum is at grain fill. Heat stress at this stage cuts test weight, and insurance adjusters will ask for field-level records.',
   'NOAA / National Weather Service (seeded for the demo)', 'processed', 1, null),
  ('2026-09-23', 'Dawson', 'NE', 40.87, -99.82, 'rain', 'Medium',
   'Dawson County, Nebraska: 2.4 inches of rain in 3 days',
   'Soybean harvest had just started. Fields will be too wet to carry combines for several days, which compresses the harvest window before corn.',
   'NOAA / National Weather Service (seeded for the demo)', 'new', 3, null),
  ('2026-09-23', 'Keith', 'NE', 41.20, -101.66, 'drought', 'Medium',
   'Keith County, Nebraska moved from D1 to D2 (severe drought)',
   'Dryland wheat seeding is under way into short moisture, and irrigated corn still needs a final watering decision.',
   'US Drought Monitor, released Sep 25 (seeded for the demo)', 'processed', 3, 2),
  ('2026-09-23', 'Douglas', 'KS', 38.88, -95.29, 'rain', 'High',
   'Douglas County, Kansas: 3.6 inches of rain in 5 days',
   'Kaw River bottom ground is saturated. Soybean harvest and wheat seeding are both on hold, and the backlog will need replanning.',
   'NOAA / National Weather Service (seeded for the demo)', 'processed', 2, null),
  ('2026-09-23', 'Saunders', 'NE', 41.23, -96.64, 'rain', 'Medium',
   'Saunders County, Nebraska: 2.1 inches of rain in 4 days',
   'Harvest paused mid-week. Growers are resequencing soybean and corn fields around the wet spots.',
   'NOAA / National Weather Service (seeded for the demo)', 'processed', 4, null),
  ('2026-09-23', 'York', 'NE', 40.87, -97.60, 'rain', 'High',
   'York County, Nebraska: 3.2 inches of rain in 4 days',
   'Standing water in low fields during peak soybean harvest. Field-work days lost this week will push corn harvest into October.',
   'NOAA / National Weather Service (seeded for the demo)', 'processed', 4, null),
  ('2026-09-23', 'Kingfisher', 'OK', 35.95, -97.94, 'drought', 'High',
   'Kingfisher County, Oklahoma moved from D1 to D3 (extreme drought)',
   'A two-category jump in one week. Wheat seeding for grazing and grain is going into dry ground, and stand establishment is at risk.',
   'US Drought Monitor, released Sep 25 (seeded for the demo)', 'processed', 5, 3),
  ('2026-09-23', 'Caddo', 'OK', 35.17, -98.38, 'heat', 'High',
   'Caddo County, Oklahoma: 3 days over 100 °F',
   'Late-season heat during cotton boll fill and ahead of wheat seeding. Yield losses will need documenting for insurance.',
   'NOAA / National Weather Service (seeded for the demo)', 'new', 5, null),
  ('2026-09-23', 'Lubbock', 'TX', 33.61, -101.82, 'drought', 'Medium',
   'Lubbock County, Texas moved from D1 to D2 (severe drought)',
   'Ogallala pumping is at seasonal limits. Growers with sorghum and wheat are deciding which fields get the last irrigation.',
   'US Drought Monitor, released Sep 25 (seeded for the demo)', 'processed', 6, 2),
  -- Week of 2026-09-16 (prior week), 4 signals for texture
  ('2026-09-16', 'Finney', 'KS', 37.99, -100.74, 'drought', 'Medium',
   'Finney County, Kansas moved from D1 to D2 (severe drought)',
   'Second week of decline across southwest Kansas.',
   'US Drought Monitor (seeded for the demo)', 'processed', 1, 2),
  ('2026-09-16', 'Lincoln', 'NE', 41.05, -100.74, 'heat', 'Medium',
   'Lincoln County, Nebraska: 3 days over 95 °F',
   'Short heat spell at corn dent stage.',
   'NOAA / National Weather Service (seeded for the demo)', 'processed', 3, null),
  ('2026-09-16', 'Grady', 'OK', 35.02, -97.88, 'drought', 'Medium',
   'Grady County, Oklahoma moved from D0 to D1 (moderate drought)',
   'Dry pattern setting in ahead of wheat seeding.',
   'US Drought Monitor (seeded for the demo)', 'processed', 5, 1),
  ('2026-09-16', 'Hale', 'TX', 34.07, -101.83, 'heat', 'High',
   'Hale County, Texas: 4 days over 99 °F',
   'Heat stress on late cotton and irrigated corn.',
   'NOAA / National Weather Service (seeded for the demo)', 'processed', 6, null);

-- ---------------------------------------------------------------- opportunities
-- History for processed signals this week. Amount uses the same formula as
-- lib/pricing.ts: round((rate x acres + setup) / 100) x 100.
insert into public.opportunities
  (signal_id, account_id, rep_id, score, lead_with, why_now, email_subject, email_body, amount, stage, ai_offline, created_at, pushed_at, sent_at)
select
  s.id, a.id, s.rep_id, v.score, v.lead_with, v.why_now, v.subject, v.body,
  (round(((p.price_list ->> v.lead_with)::numeric * a.acres + (p.price_list ->> 'setup')::numeric) / 100) * 100)::int,
  v.stage::public.opportunity_stage, false,
  v.created_at::timestamptz, v.pushed_at::timestamptz, v.sent_at::timestamptz
from (values
  -- Deaf Smith heat (Dana): 6 h median to act
  ('Hereford Feedgrain Co-op', 'Deaf Smith', 88, 'Yield & Insurance Records',
   'Four days over 98 °F hit 5,600 acres of corn and sorghum at grain fill, and Hereford has no field-level yield records for the claim.',
   'Heat this week and your sorghum claim',
   E'Rick,\n\nFour straight days over 98 °F in Deaf Smith County landed right on your sorghum at grain fill. If test weights come in light, the adjuster will want field-by-field records.\n\nYield & Insurance Records builds that file as harvest runs, so the claim is ready when you are.\n\nCould we take 15 minutes this week to set it up before your combines roll?\n\nDana',
   'sent', '2026-09-23 07:10+00', '2026-09-23 12:40+00', '2026-09-23 14:05+00'),
  ('Dawn Farms', 'Deaf Smith', 74, 'Yield & Insurance Records',
   'Dawn Farms already plans field work with us; the heat week makes documented yield loss the next thing they need.',
   'Documenting this week''s heat on your corn',
   E'Megan,\n\nThe four days over 98 °F in Deaf Smith County came at a bad moment for late corn. You already use Field-Work Planner, so adding Yield & Insurance Records ties the heat to each field''s yield automatically.\n\nDo you have 15 minutes Thursday to walk through it?\n\nDana',
   'pushed', '2026-09-23 07:10+00', '2026-09-23 13:15+00', null),
  ('Bootleg Corner Ag', 'Deaf Smith', 61, 'Yield & Insurance Records',
   'Bootleg Corner is a prospect with 1,400 acres of sorghum in the heat zone and no records system for a loss claim.',
   'Heat on your sorghum: records for the claim',
   E'Juan,\n\nDeaf Smith County just had four days over 98 °F with sorghum at grain fill. If you end up filing, clean field-level yield records make the difference in how fast a claim settles.\n\nCould I show you how we build that file in 15 minutes?\n\nDana',
   'sent', '2026-09-23 07:10+00', '2026-09-23 11:50+00', '2026-09-23 16:20+00'),
  -- Douglas rain (Rep 2): 11 h
  ('Baldwin Creek Farms', 'Douglas', 81, 'Field-Work Planner',
   'Three and a half inches of rain stopped soybean harvest and wheat seeding at once; Baldwin Creek needs to resequence both.',
   'Replanning harvest after 3.6 inches',
   E'Amy,\n\nDouglas County took 3.6 inches in five days, which stalls soybeans and wheat seeding together. Field-Work Planner shows which fields dry first so the crew goes where it can work.\n\nCan we spend 15 minutes on it this week?',
   'sent', '2026-09-23 08:00+00', '2026-09-23 18:30+00', '2026-09-24 09:00+00'),
  ('Kaw Valley Growers', 'Douglas', 69, 'Field-Work Planner',
   'Kaw Valley farms 2,400 acres of river-bottom ground that is now saturated, with no planning tool for the backlog.',
   'Wet bottoms and a harvest backlog',
   E'Ben,\n\nThe Kaw bottoms are saturated after 3.6 inches in five days. Field-Work Planner uses forecast and soil conditions to rank which fields to run first once it dries.\n\nWould 15 minutes this week work to see it on your ground?',
   'pushed', '2026-09-23 08:00+00', '2026-09-23 20:10+00', null),
  -- Keith drought (Rep 3): 29 h
  ('Ogallala Pivot Co.', 'Keith', 79, 'Irrigation Scheduling',
   'Keith County slipped to D2 while Ogallala Pivot still has corn needing a last watering call and no scheduling module.',
   'D2 in Keith County: your last corn watering',
   E'Joan,\n\nKeith County moved to severe drought this week. Irrigation Scheduling uses soil moisture and ET to tell you whether that last pass on corn pays for itself.\n\nCould we look at your pivots together for 15 minutes?',
   'sent', '2026-09-23 09:00+00', '2026-09-24 13:00+00', '2026-09-24 15:30+00'),
  ('North Platte Irrigators', 'Keith', 72, 'Irrigation Scheduling',
   'North Platte Irrigators runs 4,800 pivot acres next to the new D2 area and schedules water by calendar today.',
   'Drought next door: scheduling your water',
   E'Greg,\n\nSevere drought moved into Keith County, right next to your pivots. Irrigation Scheduling moves you from calendar watering to soil-moisture watering.\n\nDo you have 15 minutes this week?',
   'pushed', '2026-09-23 09:00+00', '2026-09-24 15:40+00', null),
  ('Grant Dryland Partners', 'Keith', 55, 'Irrigation Scheduling',
   'Grant Dryland is seeding wheat into short moisture; limited irrigated acres make this a lighter fit.',
   'Seeding wheat into D2',
   E'Kyle,\n\nWith the county next door now in D2, moisture at seeding matters more than usual. Irrigation Scheduling can help on the acres you do water.\n\nWorth a 15-minute look?',
   'draft', '2026-09-23 09:00+00', null, null),
  -- Saunders rain (Rep 4): 9 h
  ('Wahoo Grain Growers', 'Saunders', 77, 'Field-Work Planner',
   'Two inches of rain paused Wahoo''s harvest mid-week, and they are resequencing 2,900 acres by hand.',
   'Resequencing harvest after the rain',
   E'Mike,\n\nSaunders County''s 2.1 inches stopped harvest mid-week. Field-Work Planner ranks your fields by when they will carry a combine again.\n\nCan we take 15 minutes on it?',
   'sent', '2026-09-23 08:30+00', '2026-09-23 17:10+00', '2026-09-24 08:15+00'),
  ('Ashland Bottom Farms', 'Saunders', 52, 'Field-Work Planner',
   'Ashland Bottom has 1,400 acres of soybeans on low ground that will stay wet longest.',
   'Wet low ground and your soybeans',
   E'Nora,\n\nThe rain left your bottom ground wettest in the county. Field-Work Planner can help decide what to run first.\n\n15 minutes this week?',
   'draft', '2026-09-23 08:30+00', null, null),
  -- York rain (Rep 4)
  ('York County Seed Farms', 'York', 84, 'Field-Work Planner',
   'York took 3.2 inches at peak soybean harvest; York County Seed has 3,600 acres and a seed-quality deadline.',
   '3.2 inches at peak harvest',
   E'Paula,\n\nYork County''s 3.2 inches landed at peak soybean harvest. Field-Work Planner shows which fields reopen first so seed quality holds.\n\nCould we talk for 15 minutes Thursday?',
   'pushed', '2026-09-23 08:30+00', '2026-09-23 16:50+00', null),
  ('Waco Family Farms', 'York', 66, 'Field-Work Planner',
   'Waco Family Farms is a prospect losing field days this week with corn harvest queued behind soybeans.',
   'Lost field days this week',
   E'Quinn,\n\nThe rain in York County cost most growers four field days. Field-Work Planner helps win them back by sequencing fields as they dry.\n\nWould a 15-minute call work?',
   'pushed', '2026-09-23 08:30+00', '2026-09-23 18:05+00', null),
  -- Kingfisher drought (Rep 5): 52 h, low capture
  ('Kingfisher Wheat Co-op', 'Kingfisher', 86, 'Irrigation Scheduling',
   'Kingfisher jumped two drought categories in one week while the co-op''s 4,400 acres of wheat are being seeded.',
   'Two drought categories in one week',
   E'Sam,\n\nKingfisher County went from D1 to D3 this week, right as wheat goes in. Irrigation Scheduling helps you put limited water where stands are most at risk.\n\nCan we take 15 minutes this week?',
   'pushed', '2026-09-23 10:00+00', '2026-09-25 04:00+00', null),
  ('Hennessey Farms', 'Kingfisher', 63, 'Irrigation Scheduling',
   'Hennessey is seeding 1,600 acres of wheat into extreme drought with no moisture data.',
   'Seeding into D3',
   E'Tina,\n\nKingfisher County is now in extreme drought. Irrigation Scheduling shows soil moisture by field before you seed.\n\n15 minutes this week?',
   'draft', '2026-09-23 10:00+00', null, null),
  ('El Reno Grain', 'Kingfisher', 71, 'Irrigation Scheduling',
   'El Reno borders the D3 jump and has 2,700 acres of wheat and soybeans on the edge of it.',
   'Drought next door in Kingfisher',
   E'Ulises,\n\nThe county just north of you jumped to D3 this week. Irrigation Scheduling can show where your fields stand.\n\nWorth 15 minutes?',
   'draft', '2026-09-23 10:00+00', null, null),
  ('Guthrie Ag Partners', 'Kingfisher', 58, 'Irrigation Scheduling',
   'Guthrie owns two modules already; irrigation is the gap as drought spreads from Kingfisher.',
   'Adding irrigation to your FieldSense',
   E'Vera,\n\nYou already run Field-Work Planner and Yield & Insurance. With drought spreading from Kingfisher, Irrigation Scheduling closes the loop.\n\n15 minutes this week?',
   'draft', '2026-09-23 10:00+00', null, null),
  ('Enid Plains Farms', 'Kingfisher', 80, 'Irrigation Scheduling',
   'Enid Plains has 3,500 wheat acres next to the D3 area and schedules water by feel.',
   'Extreme drought next door',
   E'Walt,\n\nKingfisher County moved to D3 this week, right on your southern line. Irrigation Scheduling turns soil-moisture data into a watering plan.\n\nCould we take 15 minutes?',
   'draft', '2026-09-23 10:00+00', null, null),
  -- Lubbock drought (Rep 6): 41 h
  ('Lubbock Cotton & Grain', 'Lubbock', 83, 'Irrigation Scheduling',
   'Lubbock Cotton & Grain is choosing which of 5,100 acres get the last Ogallala water now that the county is in D2.',
   'Which fields get the last water',
   E'Yolanda,\n\nLubbock County moved to severe drought with pumping at its limits. Irrigation Scheduling ranks your fields by what the last water is worth.\n\nCan we spend 15 minutes on it?',
   'sent', '2026-09-23 09:30+00', '2026-09-25 02:00+00', '2026-09-25 14:00+00'),
  ('Plainview Irrigated Farms', 'Lubbock', 76, 'Irrigation Scheduling',
   'Plainview has 3,900 irrigated acres beside the D2 area and no scheduling module.',
   'Drought moving north toward Hale',
   E'Zach,\n\nSevere drought reached Lubbock County this week. Irrigation Scheduling can stretch your water across corn and cotton.\n\n15 minutes this week?',
   'draft', '2026-09-23 09:30+00', null, null),
  ('Levelland Sorghum Co.', 'Lubbock', 64, 'Irrigation Scheduling',
   'Levelland grows sorghum and wheat next to the new D2 area with limited water.',
   'Sorghum, wheat and D2',
   E'Brenda,\n\nThe drought just stepped up next door in Lubbock County. Irrigation Scheduling helps decide where water goes first.\n\nWorth a 15-minute look?',
   'draft', '2026-09-23 09:30+00', null, null),
  ('Tahoka Family Farms', 'Lubbock', 47, 'Yield & Insurance Records',
   'Tahoka already owns irrigation and planning; records are the only gap, and the drought impact is indirect.',
   'Records for a dry season',
   E'Cody,\n\nWith drought spreading across the South Plains, yield records by field make any claim simpler.\n\n15 minutes sometime this week?',
   'draft', '2026-09-23 09:30+00', null, null)
) as v(account_name, signal_county, score, lead_with, why_now, subject, body, stage, created_at, pushed_at, sent_at)
join public.accounts a on a.name = v.account_name
join public.signals s on s.county = v.signal_county and s.week_of = '2026-09-23'
cross join public.settings p;
