-- Signal Desk seed data. Generated by transform.py from the demo batch; run after schema.sql.

-- Synthetic accounts and reps; real Plains county names; prior weeks are seeded history.

TRUNCATE opportunities, signals, accounts, reps, settings RESTART IDENTITY CASCADE;

INSERT INTO reps (id, name, territory_name, counties, quota_quarterly, is_manager) VALUES
('REP-01', 'Jordan Ellsworth', 'Southwest Kansas', ARRAY['Finney County, KS','Grant County, KS','Seward County, KS']::text[], 180000, false),
('REP-02', 'Priya Nathan', 'Northwest & Central Kansas', ARRAY['Thomas County, KS','Sherman County, KS','Ford County, KS']::text[], 300000, false),
('REP-03', 'Marcus Deleon', 'Southwest Nebraska', ARRAY['Perkins County, NE','Chase County, NE','Dundy County, NE']::text[], 240000, false),
('REP-04', 'Renee Okafor', 'Oklahoma Panhandle', ARRAY['Texas County, OK','Beaver County, OK','Cimarron County, OK']::text[], 240000, false),
('REP-05', 'Tyler Bramlett', 'Texas Panhandle', ARRAY['Deaf Smith County, TX','Dallam County, TX','Moore County, TX']::text[], 210000, false),
('REP-06', 'Sofia Marchetti', 'Nebraska Panhandle', ARRAY['Box Butte County, NE','Cheyenne County, NE','Keith County, NE']::text[], 180000, false),
('MGR-01', 'Plains Region Manager', 'Plains region (all)', ARRAY[]::text[], 0, true);

INSERT INTO accounts (id, name, county, state, lat, lng, crops, acres, modules_owned, customer_status, contact_name, contact_email, last_contact, rep_id) VALUES
('ACC-001', 'Whitfield Land & Cattle Co.', 'Grant County', 'KS', 37.5177, -101.4147, ARRAY['Corn','Sorghum']::text[], 2200, ARRAY[]::text[], 'Prospect', 'Mary Esch', 'mary.esch1@whitfieldag.example.com', '2026-09-12', 'REP-01'),
('ACC-002', 'Wiens Family Farm', 'Grant County', 'KS', 37.4574, -101.2992, ARRAY['Wheat','Sorghum']::text[], 1200, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'Carol Friesen', 'carol.friesen2@wiensag.example.com', '2026-09-10', 'REP-01'),
('ACC-003', 'Neufeld Grain Co.', 'Dundy County', 'NE', 40.2783, -101.7756, ARRAY['Corn','Wheat']::text[], 2800, ARRAY[]::text[], 'Prospect', 'Robert Ehler', 'robert.ehler3@neufeldag.example.com', '2026-06-05', 'REP-03'),
('ACC-004', 'Friesen Agri-Services', 'Beaver County', 'OK', 36.7304, -100.5578, ARRAY['Sorghum','Wheat']::text[], 1600, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'Ruth Esch', 'ruth.esch4@friesenag.example.com', '2026-06-08', 'REP-04'),
('ACC-005', 'Regier Farms', 'Ford County', 'KS', 37.5842, -99.8704, ARRAY['Wheat','Sorghum']::text[], 800, ARRAY[]::text[], 'Prospect', 'Mark Haas', 'mark.haas5@regierag.example.com', '2026-09-09', 'REP-02'),
('ACC-006', 'Voss Ag Partners', 'Beaver County', 'OK', 36.7685, -100.511, ARRAY['Wheat','Sorghum']::text[], 2200, ARRAY[]::text[], 'Prospect', 'Mark Lindqvist', 'mark.lindqvist6@vossag.example.com', '2026-09-13', 'REP-04'),
('ACC-007', 'Janzen Land & Cattle Co.', 'Deaf Smith County', 'TX', 34.9836, -102.71, ARRAY['Corn','Silage']::text[], 2200, ARRAY[]::text[], 'Prospect', 'Ruth Krueger', 'ruth.krueger7@janzenag.example.com', '2026-08-19', 'REP-05'),
('ACC-008', 'Brandt Ranch', 'Dallam County', 'TX', 36.2898, -102.5787, ARRAY['Wheat','Corn']::text[], 4200, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'Donna Klein', 'donna.klein8@brandtag.example.com', '2026-08-09', 'REP-05'),
('ACC-009', 'Hartman Family Farm', 'Cimarron County', 'OK', 36.6547, -102.4986, ARRAY['Wheat','Sorghum']::text[], 1600, ARRAY[]::text[], 'Prospect', 'Sandra Ehler', 'sandra.ehler9@hartmanag.example.com', '2026-06-21', 'REP-04'),
('ACC-010', 'Voss Ranch', 'Sherman County', 'KS', 39.2534, -101.6564, ARRAY['Corn']::text[], 5000, ARRAY['Irrigation Scheduling','Yield & Insurance Records']::text[], 'Customer', 'Ruth Haas', 'ruth.haas10@vossag.example.com', '2026-09-09', 'REP-02'),
('ACC-011', 'Peters Family Farm', 'Texas County', 'OK', 36.7786, -101.4911, ARRAY['Wheat','Sorghum']::text[], 4200, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'Daniel Reyes', 'daniel.reyes11@petersag.example.com', '2026-06-07', 'REP-04'),
('ACC-012', 'Kaufman Agri-Services', 'Chase County', 'NE', 40.5865, -101.7103, ARRAY['Corn']::text[], 2800, ARRAY[]::text[], 'Prospect', 'Kevin Ehler', 'kevin.ehler12@kaufmanag.example.com', '2026-06-24', 'REP-03'),
('ACC-013', 'Bontrager Farming LLC', 'Texas County', 'OK', 36.7019, -101.4017, ARRAY['Wheat','Sorghum']::text[], 1600, ARRAY['Irrigation Scheduling','Field-Work Planner']::text[], 'Customer', 'Donna Schmidt', 'donna.schmidt13@bontragerag.example.com', '2026-07-24', 'REP-04'),
('ACC-014', 'Reimer Grain Co.', 'Dallam County', 'TX', 36.1796, -102.6599, ARRAY['Corn']::text[], 2200, ARRAY['Irrigation Scheduling','Yield & Insurance Records']::text[], 'Customer', 'Donna Voss', 'donna.voss14@reimerag.example.com', '2026-06-29', 'REP-05'),
('ACC-015', 'Castaneda Farming LLC', 'Moore County', 'TX', 35.8951, -101.9536, ARRAY['Corn','Wheat']::text[], 5000, ARRAY[]::text[], 'Prospect', 'Karen Krueger', 'karen.krueger15@castanedaag.example.com', '2026-08-25', 'REP-05'),
('ACC-016', 'Alvarado Bros. Farms', 'Grant County', 'KS', 37.5629, -101.4105, ARRAY['Wheat','Sorghum']::text[], 2200, ARRAY[]::text[], 'Prospect', 'David Toews', 'david.toews16@alvaradoag.example.com', '2026-08-17', 'REP-01'),
('ACC-017', 'Duerksen Grain Co.', 'Seward County', 'KS', 37.294, -100.8735, ARRAY['Corn']::text[], 6500, ARRAY['Irrigation Scheduling']::text[], 'Customer', 'Robert Peters', 'robert.peters17@duerksenag.example.com', '2026-09-05', 'REP-01'),
('ACC-018', 'Schmidt Bros. Farms', 'Sherman County', 'KS', 39.4135, -101.6981, ARRAY['Wheat','Sunflowers']::text[], 2200, ARRAY[]::text[], 'Prospect', 'James Voss', 'james.voss18@schmidtag.example.com', '2026-06-29', 'REP-02'),
('ACC-019', 'Hartman Ag Partners', 'Thomas County', 'KS', 39.3969, -101.0317, ARRAY['Corn','Wheat']::text[], 800, ARRAY[]::text[], 'Prospect', 'Robert Reyes', 'robert.reyes19@hartmanag.example.com', '2026-05-31', 'REP-02'),
('ACC-020', 'Weber Land & Cattle Co.', 'Cheyenne County', 'NE', 41.1165, -103.1119, ARRAY['Wheat']::text[], 5000, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'Brian Carver', 'brian.carver20@weberag.example.com', '2026-05-26', 'REP-06'),
('ACC-021', 'Sorensen Ag Partners', 'Cimarron County', 'OK', 36.7973, -102.6505, ARRAY['Corn','Wheat']::text[], 4200, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'Sandra Epp', 'sandra.epp21@sorensenag.example.com', '2026-07-07', 'REP-04'),
('ACC-022', 'Suderman Ranch', 'Finney County', 'KS', 38.0753, -100.5921, ARRAY['Corn','Sorghum']::text[], 800, ARRAY[]::text[], 'Prospect', 'Linda Hartman', 'linda.hartman22@sudermanag.example.com', '2026-07-14', 'REP-01'),
('ACC-023', 'Dietz Ag Partners', 'Thomas County', 'KS', 39.402, -100.9439, ARRAY['Wheat','Sunflowers']::text[], 2200, ARRAY['Field-Work Planner']::text[], 'Customer', 'Karen Haas', 'karen.haas23@dietzag.example.com', '2026-09-19', 'REP-02'),
('ACC-024', 'Lindqvist Ag Partners', 'Chase County', 'NE', 40.6258, -101.7434, ARRAY['Corn','Soybeans']::text[], 5000, ARRAY[]::text[], 'Prospect', 'Ruth Dietz', 'ruth.dietz24@lindqvistag.example.com', '2026-08-26', 'REP-03'),
('ACC-025', 'Hartman Agri-Services', 'Perkins County', 'NE', 40.8485, -101.7345, ARRAY['Corn']::text[], 1200, ARRAY[]::text[], 'Prospect', 'Susan Friesen', 'susan.friesen25@hartmanag.example.com', '2026-08-22', 'REP-03'),
('ACC-026', 'Ratzlaff Farms & Feedlot', 'Finney County', 'KS', 38.0972, -100.7706, ARRAY['Corn','Sorghum']::text[], 2200, ARRAY[]::text[], 'Prospect', 'Mary Friesen', 'mary.friesen26@ratzlaffag.example.com', '2026-09-04', 'REP-01'),
('ACC-027', 'Thiessen Farms', 'Box Butte County', 'NE', 42.1399, -103.1195, ARRAY['Dry beans','Wheat']::text[], 2800, ARRAY[]::text[], 'Prospect', 'Steven Wiens', 'steven.wiens27@thiessenag.example.com', '2026-08-20', 'REP-06'),
('ACC-028', 'Suderman Agri-Services', 'Cimarron County', 'OK', 36.8266, -102.4108, ARRAY['Wheat']::text[], 1600, ARRAY['Irrigation Scheduling']::text[], 'Customer', 'Brian Castaneda', 'brian.castaneda28@sudermanag.example.com', '2026-06-10', 'REP-04'),
('ACC-029', 'Hartman Grain Co.', 'Finney County', 'KS', 38.1568, -100.6852, ARRAY['Corn','Sorghum']::text[], 800, ARRAY[]::text[], 'Prospect', 'Kevin Alvarado', 'kevin.alvarado29@hartmanag.example.com', '2026-07-27', 'REP-01'),
('ACC-030', 'Friesen Farms', 'Cheyenne County', 'NE', 41.1362, -103.0871, ARRAY['Wheat','Corn']::text[], 1200, ARRAY[]::text[], 'Prospect', 'Robert Ehler', 'robert.ehler30@friesenag.example.com', '2026-07-27', 'REP-06'),
('ACC-031', 'Duerksen Family Farm', 'Deaf Smith County', 'TX', 34.8529, -102.5007, ARRAY['Corn','Wheat']::text[], 800, ARRAY[]::text[], 'Prospect', 'Sandra Brandt', 'sandra.brandt31@duerksenag.example.com', '2026-07-19', 'REP-05'),
('ACC-032', 'Carver Agri-Services', 'Dundy County', 'NE', 40.1277, -101.7963, ARRAY['Wheat']::text[], 2800, ARRAY['Field-Work Planner','Irrigation Scheduling']::text[], 'Customer', 'Daniel Duerksen', 'daniel.duerksen32@carverag.example.com', '2026-06-22', 'REP-03'),
('ACC-033', 'Unruh Land & Cattle Co.', 'Beaver County', 'OK', 36.7764, -100.5344, ARRAY['Wheat','Sorghum']::text[], 3500, ARRAY[]::text[], 'Prospect', 'Robert Miller', 'robert.miller33@unruhag.example.com', '2026-05-16', 'REP-04'),
('ACC-034', 'Lindqvist Bros. Farms', 'Seward County', 'KS', 37.2981, -100.8035, ARRAY['Corn']::text[], 1200, ARRAY['Field-Work Planner','Irrigation Scheduling']::text[], 'Customer', 'Carol Voss', 'carol.voss34@lindqvistag.example.com', '2026-09-11', 'REP-01'),
('ACC-035', 'Weber Grain Co.', 'Keith County', 'NE', 41.1896, -101.5487, ARRAY['Corn','Soybeans']::text[], 1600, ARRAY['Yield & Insurance Records','Field-Work Planner']::text[], 'Customer', 'Sharon Alvarado', 'sharon.alvarado35@weberag.example.com', '2026-06-16', 'REP-06'),
('ACC-036', 'Miller Agri-Services', 'Keith County', 'NE', 41.1755, -101.6918, ARRAY['Corn']::text[], 1200, ARRAY[]::text[], 'Prospect', 'Michael Krueger', 'michael.krueger36@millerag.example.com', '2026-06-14', 'REP-06'),
('ACC-037', 'Reimer Family Farm', 'Dallam County', 'TX', 36.1749, -102.7298, ARRAY['Corn','Wheat']::text[], 6500, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'David Peters', 'david.peters37@reimerag.example.com', '2026-06-04', 'REP-05'),
('ACC-038', 'Yoder Land & Cattle Co.', 'Perkins County', 'NE', 40.769, -101.698, ARRAY['Corn','Wheat']::text[], 2800, ARRAY[]::text[], 'Prospect', 'Mary Klein', 'mary.klein38@yoderag.example.com', '2026-08-29', 'REP-03'),
('ACC-039', 'Suderman Land & Cattle Co.', 'Moore County', 'TX', 35.7201, -101.9946, ARRAY['Corn','Wheat']::text[], 800, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'Daniel Friesen', 'daniel.friesen39@sudermanag.example.com', '2026-06-23', 'REP-05'),
('ACC-040', 'Goertzen Agri-Services', 'Seward County', 'KS', 37.2173, -100.9789, ARRAY['Corn','Wheat']::text[], 6500, ARRAY['Yield & Insurance Records']::text[], 'Customer', 'Michael Castaneda', 'michael.castaneda40@goertzenag.example.com', '2026-06-20', 'REP-01'),
('ACC-041', 'Becker Grain Co.', 'Sherman County', 'KS', 39.2657, -101.7943, ARRAY['Wheat','Sunflowers']::text[], 6500, ARRAY['Irrigation Scheduling']::text[], 'Customer', 'Nancy Neufeld', 'nancy.neufeld41@beckerag.example.com', '2026-06-23', 'REP-02'),
('ACC-042', 'Yoder Ag Partners', 'Ford County', 'KS', 37.6838, -100.0054, ARRAY['Wheat','Corn']::text[], 1200, ARRAY['Field-Work Planner','Irrigation Scheduling']::text[], 'Customer', 'Susan Friesen', 'susan.friesen42@yoderag.example.com', '2026-05-28', 'REP-02'),
('ACC-043', 'Kaufman Ranch', 'Chase County', 'NE', 40.5153, -101.7564, ARRAY['Corn','Wheat']::text[], 1600, ARRAY[]::text[], 'Prospect', 'Paul Ratzlaff', 'paul.ratzlaff43@kaufmanag.example.com', '2026-08-29', 'REP-03'),
('ACC-044', 'Friesen Family Farm', 'Deaf Smith County', 'TX', 35.0299, -102.5279, ARRAY['Corn','Silage']::text[], 800, ARRAY[]::text[], 'Prospect', 'Susan Bontrager', 'susan.bontrager44@friesenag.example.com', '2026-08-14', 'REP-05'),
('ACC-045', 'Lindqvist Grain Co.', 'Box Butte County', 'NE', 42.2239, -103.1784, ARRAY['Wheat','Corn']::text[], 2200, ARRAY['Irrigation Scheduling','Field-Work Planner']::text[], 'Customer', 'Paul Haas', 'paul.haas45@lindqvistag.example.com', '2026-06-24', 'REP-06'),
('ACC-046', 'Voss Land & Cattle Co.', 'Perkins County', 'NE', 40.7652, -101.637, ARRAY['Corn','Wheat']::text[], 6500, ARRAY['Field-Work Planner','Irrigation Scheduling']::text[], 'Customer', 'Linda Krueger', 'linda.krueger46@vossag.example.com', '2026-05-12', 'REP-03'),
('ACC-047', 'Kaufman Bros. Farms', 'Dundy County', 'NE', 40.1315, -101.6471, ARRAY['Corn','Wheat']::text[], 800, ARRAY['Field-Work Planner']::text[], 'Customer', 'Paul Suderman', 'paul.suderman47@kaufmanag.example.com', '2026-07-20', 'REP-03'),
('ACC-048', 'Ehler Agri-Services', 'Keith County', 'NE', 41.2044, -101.5375, ARRAY['Corn']::text[], 4200, ARRAY[]::text[], 'Prospect', 'David Krueger', 'david.krueger48@ehlerag.example.com', '2026-07-29', 'REP-06'),
('ACC-049', 'Becker Ranch', 'Moore County', 'TX', 35.8478, -101.8063, ARRAY['Cotton','Corn']::text[], 6500, ARRAY[]::text[], 'Prospect', 'Ruth Bontrager', 'ruth.bontrager49@beckerag.example.com', '2026-07-29', 'REP-05'),
('ACC-050', 'Neufeld Ranch', 'Cheyenne County', 'NE', 41.2472, -102.9035, ARRAY['Wheat','Corn']::text[], 3500, ARRAY[]::text[], 'Prospect', 'Linda Toews', 'linda.toews50@neufeldag.example.com', '2026-07-25', 'REP-06');

INSERT INTO signals (id, week_of, county, state, lat, lng, type, severity, headline, detail, source, target_module, status, rep_id) VALUES
('SIG-0001', '2026-08-31', 'Sherman County', 'KS', 39.35, -101.72, 'heat', 'High', 'Sherman, KS: highs above 98°F with overnight lows above 75°F during grain fill', 'Sherman County, KS forecast shows highs above 98°F with overnight lows above 75°F during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'processed', 'REP-02'),
('SIG-0002', '2026-08-31', 'Dallam County', 'TX', 36.28, -102.6, 'heat', 'Medium', 'Dallam, TX: highs above 95°F for 3+ consecutive days during grain fill', 'Dallam County, TX forecast shows highs above 95°F for 3+ consecutive days during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'processed', 'REP-05'),
('SIG-0003', '2026-08-31', 'Cimarron County', 'OK', 36.75, -102.52, 'drought', 'High', 'Cimarron, OK moved D3 → D4 (Exceptional Drought)', 'Cimarron County, OK drought category worsened to D4 (Exceptional Drought) this week (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'processed', 'REP-04'),
('SIG-0004', '2026-08-31', 'Perkins County', 'NE', 40.85, -101.65, 'heat', 'High', 'Perkins, NE: highs above 98°F with overnight lows above 75°F during grain fill', 'Perkins County, NE forecast shows highs above 98°F with overnight lows above 75°F during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'processed', 'REP-03'),
('SIG-0005', '2026-09-07', 'Chase County', 'NE', 40.52, -101.7, 'drought', 'High', 'Chase, NE moved D2 → D3 (Extreme Drought)', 'Chase County, NE drought category worsened to D3 (Extreme Drought) this week (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'processed', 'REP-03'),
('SIG-0006', '2026-09-07', 'Sherman County', 'KS', 39.35, -101.72, 'rain', 'Medium', 'Sherman, KS: 2.5in of rain over 4 days', 'Sherman County, KS 7-day forecast shows 2.5in of rain over 4 days, closing multiple field-work days (NOAA).', 'NOAA', 'Field-Work Planner', 'processed', 'REP-02'),
('SIG-0007', '2026-09-07', 'Beaver County', 'OK', 36.75, -100.48, 'rain', 'Medium', 'Beaver, OK: 1.8in of rain plus high winds', 'Beaver County, OK 7-day forecast shows 1.8in of rain plus high winds, closing multiple field-work days (NOAA).', 'NOAA', 'Field-Work Planner', 'processed', 'REP-04'),
('SIG-0008', '2026-09-07', 'Dundy County', 'NE', 40.18, -101.69, 'heat', 'High', 'Dundy, NE: a hail warning alongside extreme heat during grain fill', 'Dundy County, NE forecast shows a hail warning alongside extreme heat during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'processed', 'REP-03'),
('SIG-0009', '2026-09-14', 'Keith County', 'NE', 41.2, -101.66, 'heat', 'Medium', 'Keith, NE: highs above 95°F for 3+ consecutive days during grain fill', 'Keith County, NE forecast shows highs above 95°F for 3+ consecutive days during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'processed', 'REP-06'),
('SIG-0010', '2026-09-14', 'Cheyenne County', 'NE', 41.22, -102.99, 'heat', 'High', 'Cheyenne, NE: highs above 98°F with overnight lows above 75°F during grain fill', 'Cheyenne County, NE forecast shows highs above 98°F with overnight lows above 75°F during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'processed', 'REP-06'),
('SIG-0011', '2026-09-14', 'Deaf Smith County', 'TX', 34.97, -102.6, 'heat', 'Medium', 'Deaf Smith, TX: highs above 95°F for 3+ consecutive days during grain fill', 'Deaf Smith County, TX forecast shows highs above 95°F for 3+ consecutive days during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'processed', 'REP-05'),
('SIG-0012', '2026-09-21', 'Seward County', 'KS', 37.19, -100.85, 'drought', 'High', 'Seward, KS moved D2 → D3 (Extreme Drought)', 'Seward County, KS drought category worsened to D3 (Extreme Drought) this week (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'processed', 'REP-01'),
('SIG-0013', '2026-09-21', 'Sherman County', 'KS', 39.35, -101.72, 'drought', 'Medium', 'Sherman, KS moved D1 → D2 (Severe Drought)', 'Sherman County, KS drought category worsened to D2 (Severe Drought) this week (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'processed', 'REP-02'),
('SIG-0014', '2026-09-21', 'Cimarron County', 'OK', 36.75, -102.52, 'drought', 'Medium', 'Cimarron, OK moved D0 → D1 (Moderate Drought)', 'Cimarron County, OK drought category worsened to D1 (Moderate Drought) this week (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'processed', 'REP-04'),
('SIG-0015', '2026-09-21', 'Ford County', 'KS', 37.69, -99.89, 'drought', 'Medium', 'Ford, KS moved D1 → D2 (Severe Drought)', 'Ford County, KS drought category worsened to D2 (Severe Drought) this week (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'processed', 'REP-02'),
('SIG-0016', '2026-09-28', 'Moore County', 'TX', 35.84, -101.89, 'heat', 'High', 'Moore, TX: a hail warning alongside extreme heat during grain fill', 'Moore County, TX forecast shows a hail warning alongside extreme heat during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'new', 'REP-05'),
('SIG-0017', '2026-09-28', 'Seward County', 'KS', 37.19, -100.85, 'rain', 'High', 'Seward, KS: 3.1in of rain with flooding risk', 'Seward County, KS 7-day forecast shows 3.1in of rain with flooding risk, closing multiple field-work days (NOAA).', 'NOAA', 'Field-Work Planner', 'new', 'REP-01'),
('SIG-0018', '2026-09-28', 'Keith County', 'NE', 41.2, -101.66, 'rain', 'Medium', 'Keith, NE: 2.5in of rain over 4 days', 'Keith County, NE 7-day forecast shows 2.5in of rain over 4 days, closing multiple field-work days (NOAA).', 'NOAA', 'Field-Work Planner', 'new', 'REP-06'),
('SIG-0019', '2026-09-28', 'Cheyenne County', 'NE', 41.22, -102.99, 'drought', 'High', 'Cheyenne, NE moved D3 → D4 (Exceptional Drought)', 'Cheyenne County, NE drought category worsened to D4 (Exceptional Drought) this week; exceptional drought persists across the Nebraska Panhandle while southwest Nebraska received relief rain earlier in September (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'new', 'REP-06'),
('SIG-0020', '2026-09-28', 'Cimarron County', 'OK', 36.75, -102.52, 'drought', 'High', 'Cimarron, OK moved D3 → D4 (Exceptional Drought)', 'Cimarron County, OK drought category worsened to D4 (Exceptional Drought) this week (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'new', 'REP-04'),
('SIG-0021', '2026-09-28', 'Sherman County', 'KS', 39.35, -101.72, 'drought', 'Medium', 'Sherman, KS moved D1 → D2 (Severe Drought)', 'Sherman County, KS drought category worsened to D2 (Severe Drought) this week (US Drought Monitor).', 'US Drought Monitor', 'Irrigation Scheduling', 'new', 'REP-02'),
('SIG-0022', '2026-09-28', 'Grant County', 'KS', 37.56, -101.31, 'heat', 'High', 'Grant, KS: a hail warning alongside extreme heat during grain fill', 'Grant County, KS forecast shows a hail warning alongside extreme heat during grain fill and harvest dry-down (NOAA).', 'NOAA', 'Yield & Insurance Records', 'new', 'REP-01'),
('SIG-0023', '2026-09-28', 'Finney County', 'KS', 38.04, -100.74, 'drought', 'High', 'Finney, KS moved D2 → D3 (Extreme Drought)', 'Finney County, KS drought category worsened from D2 to D3 (Extreme Drought) this week; third consecutive week of decline. Irrigated corn and sorghum are past silking and district water allocation decisions are being made now (US Drought Monitor, released Sep 25).', 'US Drought Monitor', 'Irrigation Scheduling', 'new', 'REP-01');

INSERT INTO opportunities (id, signal_id, account_id, rep_id, score, lead_with, why_now, email_subject, email_body, amount, stage, ai_offline, is_signal_driven, is_off_territory, sf_opportunity_id, sf_error, created_at, pushed_at, sent_at) VALUES
('OPP-0001', 'SIG-0011', 'ACC-007', 'REP-05', 36, 'Yield & Insurance Records', 'Janzen Land & Cattle Co. has 2,200 acres of corn in Deaf Smith County under highs above 95°F for 3+ consecutive days; yield loss documentation starts now if a claim follows.', 'Deaf Smith County heat during grain fill — getting your yield records in order now', 'Hi Ruth,

Deaf Smith County, TX forecast shows highs above 95°F for 3+ consecutive days during grain fill and harvest dry-down (NOAA). With 2,200 acres of corn, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Tyler Bramlett', 5800, 'pushed', false, true, false, NULL, NULL, '2026-09-16T14:00:00Z', '2026-09-18T00:00:00Z', NULL),
('OPP-0002', 'SIG-0005', 'ACC-024', 'REP-03', 93, 'Irrigation Scheduling', 'Lindqvist Ag Partners runs 5,000 acres of corn in Chase County, which D2 to D3 this week; a watering plan pays for itself in the week allocations tighten.', 'Chase County just moved to extreme drought — a watering plan for the acres you can still irrigate', 'Hi Ruth,

Chase County, NE drought category worsened to D3 (Extreme Drought) this week (US Drought Monitor). With 5,000 acres of corn, FieldSense Irrigation Scheduling can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Marcus Deleon', 22500, 'sent', false, true, false, NULL, NULL, '2026-09-07T14:00:00Z', '2026-09-09T15:00:00Z', '2026-09-20T16:30:00Z'),
('OPP-0003', 'SIG-0001', 'ACC-041', 'REP-05', 0, 'Yield & Insurance Records', 'Becker Grain Co. has 6,500 acres of wheat in Sherman County under highs above 98°F with overnight lows above 75°F; yield loss documentation starts now if a claim follows.', 'Sherman County heat during grain fill — getting your yield records in order now', 'Hi Nancy,

Sherman County, KS forecast shows highs above 98°F with overnight lows above 75°F during grain fill and harvest dry-down (NOAA). With 6,500 acres of wheat, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Tyler Bramlett', 12200, 'lost', false, true, true, NULL, NULL, '2026-09-01T14:00:00Z', '2026-09-01T15:00:00Z', '2026-09-12T16:30:00Z'),
('OPP-0004', 'SIG-0017', 'ACC-040', 'REP-01', 36, 'Field-Work Planner', 'Goertzen Agri-Services has 6,500 acres in Seward County facing 3.1in of rain with flooding risk; field-work windows are the constraint this week.', 'Seward County: 3.1in of rain with flooding risk — planning the field days you have left', 'Hi Michael,

Seward County, KS 7-day forecast shows 3.1in of rain with flooding risk, closing multiple field-work days (NOAA). With 6,500 acres of corn, FieldSense Field-Work Planner can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Jordan Ellsworth', 18800, 'pushed', false, true, false, NULL, NULL, '2026-09-29T14:00:00Z', '2026-09-29T15:00:00Z', NULL),
('OPP-0005', 'SIG-0004', 'ACC-038', 'REP-01', 20, 'Yield & Insurance Records', 'Yoder Land & Cattle Co. has 2,800 acres of corn in Perkins County under highs above 98°F with overnight lows above 75°F; yield loss documentation starts now if a claim follows.', 'Perkins County heat during grain fill — getting your yield records in order now', 'Hi Mary,

Perkins County, NE forecast shows highs above 98°F with overnight lows above 75°F during grain fill and harvest dry-down (NOAA). With 2,800 acres of corn, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Jordan Ellsworth', 6700, 'draft', false, true, true, NULL, NULL, '2026-09-01T14:00:00Z', NULL, NULL),
('OPP-0006', 'SIG-0022', 'ACC-016', 'REP-03', 17, 'Yield & Insurance Records', 'Alvarado Bros. Farms has 2,200 acres of wheat in Grant County under a hail warning alongside extreme heat; yield loss documentation starts now if a claim follows.', 'Grant County heat during grain fill — getting your yield records in order now', 'Hi David,

Grant County, KS forecast shows a hail warning alongside extreme heat during grain fill and harvest dry-down (NOAA). With 2,200 acres of wheat, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Marcus Deleon', 5800, 'draft', false, true, true, NULL, NULL, '2026-09-29T14:00:00Z', NULL, NULL),
('OPP-0007', 'SIG-0014', 'ACC-021', 'REP-04', 24, 'Irrigation Scheduling', 'Sorensen Ag Partners runs 4,200 acres of corn in Cimarron County, which D0 to D1 this week; a watering plan pays for itself in the week allocations tighten.', 'Cimarron County just moved to moderate drought — a watering plan for the acres you can still irrigate', 'Hi Sandra,

Cimarron County, OK drought category worsened to D1 (Moderate Drought) this week (US Drought Monitor). With 4,200 acres of corn, FieldSense Irrigation Scheduling can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Renee Okafor', 19300, 'pushed', false, true, false, NULL, NULL, '2026-09-26T14:00:00Z', '2026-09-21T06:00:00Z', NULL),
('OPP-0008', 'SIG-0011', 'ACC-044', 'REP-01', 51, 'Yield & Insurance Records', 'Friesen Family Farm has 800 acres of corn in Deaf Smith County under highs above 95°F for 3+ consecutive days; yield loss documentation starts now if a claim follows.', 'Deaf Smith County heat during grain fill — getting your yield records in order now', 'Hi Susan,

Deaf Smith County, TX forecast shows highs above 95°F for 3+ consecutive days during grain fill and harvest dry-down (NOAA). With 800 acres of corn, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Jordan Ellsworth', 3700, 'sent', false, true, true, NULL, NULL, '2026-09-17T14:00:00Z', '2026-09-19T15:00:00Z', '2026-09-20T16:30:00Z'),
('OPP-0009', 'SIG-0006', 'ACC-018', 'REP-02', 0, 'Field-Work Planner', 'Schmidt Bros. Farms has 2,200 acres in Sherman County facing 2.5in of rain over 4 days; field-work windows are the constraint this week.', 'Sherman County: 2.5in of rain over 4 days — planning the field days you have left', 'Hi James,

Sherman County, KS 7-day forecast shows 2.5in of rain over 4 days, closing multiple field-work days (NOAA). With 2,200 acres of wheat, FieldSense Field-Work Planner can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Priya Nathan', 8000, 'lost', false, true, false, NULL, NULL, '2026-09-13T14:00:00Z', '2026-09-14T15:00:00Z', '2026-09-29T16:30:00Z'),
('OPP-0010', 'SIG-0008', 'ACC-003', 'REP-03', 0, 'Yield & Insurance Records', 'Neufeld Grain Co. has 2,800 acres of corn in Dundy County under a hail warning alongside extreme heat; yield loss documentation starts now if a claim follows.', 'Dundy County heat during grain fill — getting your yield records in order now', 'Hi Robert,

Dundy County, NE forecast shows a hail warning alongside extreme heat during grain fill and harvest dry-down (NOAA). With 2,800 acres of corn, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Marcus Deleon', 6700, 'lost', false, true, false, NULL, NULL, '2026-09-12T14:00:00Z', '2026-09-13T15:00:00Z', '2026-09-29T16:30:00Z'),
('OPP-0011', 'SIG-0005', 'ACC-043', 'REP-03', 66, 'Irrigation Scheduling', 'Kaufman Ranch runs 1,600 acres of corn in Chase County, which D2 to D3 this week; a watering plan pays for itself in the week allocations tighten.', 'Chase County just moved to extreme drought — a watering plan for the acres you can still irrigate', 'Hi Paul,

Chase County, NE drought category worsened to D3 (Extreme Drought) this week (US Drought Monitor). With 1,600 acres of corn, FieldSense Irrigation Scheduling can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Marcus Deleon', 8900, 'sent', false, true, false, NULL, NULL, '2026-09-10T14:00:00Z', '2026-09-12T15:00:00Z', '2026-09-22T16:30:00Z'),
('OPP-0012', 'SIG-0011', 'ACC-031', 'REP-05', 89, 'Yield & Insurance Records', 'Duerksen Family Farm has 800 acres of corn in Deaf Smith County under highs above 95°F for 3+ consecutive days; yield loss documentation starts now if a claim follows.', 'Deaf Smith County heat during grain fill — getting your yield records in order now', 'Hi Sandra,

Deaf Smith County, TX forecast shows highs above 95°F for 3+ consecutive days during grain fill and harvest dry-down (NOAA). With 800 acres of corn, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Tyler Bramlett', 3700, 'sent', false, true, false, NULL, NULL, '2026-09-18T14:00:00Z', '2026-09-20T00:00:00Z', '2026-09-22T00:00:00Z'),
('OPP-0013', 'SIG-0016', 'ACC-049', 'REP-05', 33, 'Yield & Insurance Records', 'Becker Ranch has 6,500 acres of cotton in Moore County under a hail warning alongside extreme heat; yield loss documentation starts now if a claim follows.', 'Moore County heat during grain fill — getting your yield records in order now', 'Hi Ruth,

Moore County, TX forecast shows a hail warning alongside extreme heat during grain fill and harvest dry-down (NOAA). With 6,500 acres of cotton, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Tyler Bramlett', 12200, 'draft', false, true, false, NULL, NULL, '2026-09-29T14:00:00Z', NULL, NULL),
('OPP-0014', 'SIG-0001', 'ACC-018', 'REP-02', 30, 'Yield & Insurance Records', 'Schmidt Bros. Farms has 2,200 acres of wheat in Sherman County under highs above 98°F with overnight lows above 75°F; yield loss documentation starts now if a claim follows.', 'Sherman County heat during grain fill — getting your yield records in order now', 'Hi James,

Sherman County, KS forecast shows highs above 98°F with overnight lows above 75°F during grain fill and harvest dry-down (NOAA). With 2,200 acres of wheat, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Priya Nathan', 5800, 'pushed', false, true, false, NULL, NULL, '2026-09-03T14:00:00Z', '2026-09-04T15:00:00Z', NULL),
('OPP-0015', 'SIG-0018', 'ACC-036', 'REP-06', 69, 'Field-Work Planner', 'Miller Agri-Services has 1,200 acres in Keith County facing 2.5in of rain over 4 days; field-work windows are the constraint this week.', 'Keith County: 2.5in of rain over 4 days — planning the field days you have left', 'Hi Michael,

Keith County, NE 7-day forecast shows 2.5in of rain over 4 days, closing multiple field-work days (NOAA). With 1,200 acres of corn, FieldSense Field-Work Planner can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Sofia Marchetti', 5500, 'sent', false, true, false, NULL, NULL, '2026-09-29T14:00:00Z', '2026-09-30T15:00:00Z', '2026-09-30T16:30:00Z'),
('OPP-0016', 'SIG-0007', 'ACC-006', 'REP-04', 100, 'Field-Work Planner', 'Voss Ag Partners has 2,200 acres in Beaver County facing 1.8in of rain plus high winds; field-work windows are the constraint this week.', 'Beaver County: 1.8in of rain plus high winds — planning the field days you have left', 'Hi Mark,

Beaver County, OK 7-day forecast shows 1.8in of rain plus high winds, closing multiple field-work days (NOAA). With 2,200 acres of wheat, FieldSense Field-Work Planner can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Renee Okafor', 8000, 'won', false, true, false, NULL, NULL, '2026-09-12T14:00:00Z', '2026-09-07T06:00:00Z', '2026-09-07T16:00:00Z'),
('OPP-0017', 'SIG-0006', 'ACC-010', 'REP-03', 52, 'Field-Work Planner', 'Voss Ranch has 5,000 acres in Sherman County facing 2.5in of rain over 4 days; field-work windows are the constraint this week.', 'Sherman County: 2.5in of rain over 4 days — planning the field days you have left', 'Hi Ruth,

Sherman County, KS 7-day forecast shows 2.5in of rain over 4 days, closing multiple field-work days (NOAA). With 5,000 acres of corn, FieldSense Field-Work Planner can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Marcus Deleon', 15000, 'sent', false, true, true, NULL, NULL, '2026-09-11T14:00:00Z', '2026-09-11T15:00:00Z', '2026-09-21T16:30:00Z'),
('OPP-0018', 'SIG-0009', 'ACC-036', 'REP-06', 31, 'Yield & Insurance Records', 'Miller Agri-Services has 1,200 acres of corn in Keith County under highs above 95°F for 3+ consecutive days; yield loss documentation starts now if a claim follows.', 'Keith County heat during grain fill — getting your yield records in order now', 'Hi Michael,

Keith County, NE forecast shows highs above 95°F for 3+ consecutive days during grain fill and harvest dry-down (NOAA). With 1,200 acres of corn, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Sofia Marchetti', 4300, 'pushed', false, true, false, NULL, NULL, '2026-09-19T14:00:00Z', '2026-09-21T15:00:00Z', NULL),
('OPP-0019', 'SIG-0007', 'ACC-004', 'REP-04', 49, 'Field-Work Planner', 'Friesen Agri-Services has 1,600 acres in Beaver County facing 1.8in of rain plus high winds; field-work windows are the constraint this week.', 'Beaver County: 1.8in of rain plus high winds — planning the field days you have left', 'Hi Ruth,

Beaver County, OK 7-day forecast shows 1.8in of rain plus high winds, closing multiple field-work days (NOAA). With 1,600 acres of sorghum, FieldSense Field-Work Planner can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Renee Okafor', 6500, 'sent', false, true, false, NULL, NULL, '2026-09-12T14:00:00Z', '2026-09-07T06:00:00Z', '2026-09-07T15:00:00Z'),
('OPP-0020', 'SIG-0015', 'ACC-005', 'REP-02', 35, 'Irrigation Scheduling', 'Regier Farms runs 800 acres of wheat in Ford County, which D1 to D2 this week; a watering plan pays for itself in the week allocations tighten.', 'Ford County just moved to severe drought — a watering plan for the acres you can still irrigate', 'Hi Mark,

Ford County, KS drought category worsened to D2 (Severe Drought) this week (US Drought Monitor). With 800 acres of wheat, FieldSense Irrigation Scheduling can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Priya Nathan', 5700, 'pushed', false, true, false, NULL, NULL, '2026-09-22T14:00:00Z', '2026-09-23T15:00:00Z', NULL),
('OPP-0021', 'SIG-0004', 'ACC-046', 'REP-01', 47, 'Yield & Insurance Records', 'Voss Land & Cattle Co. has 6,500 acres of corn in Perkins County under highs above 98°F with overnight lows above 75°F; yield loss documentation starts now if a claim follows.', 'Perkins County heat during grain fill — getting your yield records in order now', 'Hi Linda,

Perkins County, NE forecast shows highs above 98°F with overnight lows above 75°F during grain fill and harvest dry-down (NOAA). With 6,500 acres of corn, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Jordan Ellsworth', 12200, 'sent', false, true, true, NULL, NULL, '2026-09-05T14:00:00Z', '2026-09-06T15:00:00Z', '2026-09-28T16:30:00Z'),
('OPP-0022', 'SIG-0012', 'ACC-040', 'REP-01', 32, 'Irrigation Scheduling', 'Goertzen Agri-Services runs 6,500 acres of corn in Seward County, which D2 to D3 this week; a watering plan pays for itself in the week allocations tighten.', 'Seward County just moved to extreme drought — a watering plan for the acres you can still irrigate', 'Hi Michael,

Seward County, KS drought category worsened to D3 (Extreme Drought) this week (US Drought Monitor). With 6,500 acres of corn, FieldSense Irrigation Scheduling can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Jordan Ellsworth', 28500, 'pushed', false, true, false, NULL, NULL, '2026-09-21T14:00:00Z', '2026-09-23T15:00:00Z', NULL),
('OPP-0023', 'SIG-0010', 'ACC-050', 'REP-04', 100, 'Yield & Insurance Records', 'Neufeld Ranch has 3,500 acres of wheat in Cheyenne County under highs above 98°F with overnight lows above 75°F; yield loss documentation starts now if a claim follows.', 'Cheyenne County heat during grain fill — getting your yield records in order now', 'Hi Linda,

Cheyenne County, NE forecast shows highs above 98°F with overnight lows above 75°F during grain fill and harvest dry-down (NOAA). With 3,500 acres of wheat, FieldSense Yield & Insurance Records can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Renee Okafor', 7800, 'won', false, true, true, NULL, NULL, '2026-09-15T14:00:00Z', '2026-09-14T06:00:00Z', '2026-09-15T06:00:00Z'),
('OPP-0024', NULL, 'ACC-020', 'REP-06', 0, 'Irrigation Scheduling', 'List-based prospecting: Weber Land & Cattle Co. was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Irrigation Scheduling for Weber Land & Cattle Co.', 'Hi Brian,

Checking in on Irrigation Scheduling for your 5,000 acres. Happy to walk through it when you have fifteen minutes.

Sofia Marchetti', 22500, 'lost', false, false, false, NULL, NULL, '2026-08-15T14:00:00Z', '2026-08-16T15:00:00Z', '2026-09-13T16:30:00Z'),
('OPP-0025', NULL, 'ACC-015', 'REP-05', 29, 'Yield & Insurance Records', 'List-based prospecting: Castaneda Farming LLC was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Yield & Insurance Records for Castaneda Farming LLC', 'Hi Karen,

Checking in on Yield & Insurance Records for your 5,000 acres. Happy to walk through it when you have fifteen minutes.

Tyler Bramlett', 10000, 'pushed', false, false, false, NULL, NULL, '2026-08-26T14:00:00Z', '2026-08-26T15:00:00Z', NULL),
('OPP-0026', NULL, 'ACC-048', 'REP-06', 15, 'Irrigation Scheduling', 'List-based prospecting: Ehler Agri-Services was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Irrigation Scheduling for Ehler Agri-Services', 'Hi David,

Checking in on Irrigation Scheduling for your 4,200 acres. Happy to walk through it when you have fifteen minutes.

Sofia Marchetti', 19300, 'draft', false, false, false, NULL, NULL, '2026-09-17T14:00:00Z', NULL, NULL),
('OPP-0027', NULL, 'ACC-001', 'REP-01', 23, 'Field-Work Planner', 'List-based prospecting: Whitfield Land & Cattle Co. was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Field-Work Planner for Whitfield Land & Cattle Co.', 'Hi Mary,

Checking in on Field-Work Planner for your 2,200 acres. Happy to walk through it when you have fifteen minutes.

Jordan Ellsworth', 8000, 'pushed', false, false, false, NULL, NULL, '2026-09-04T14:00:00Z', '2026-09-04T15:00:00Z', NULL),
('OPP-0028', NULL, 'ACC-015', 'REP-05', 38, 'Field-Work Planner', 'List-based prospecting: Castaneda Farming LLC was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Field-Work Planner for Castaneda Farming LLC', 'Hi Karen,

Checking in on Field-Work Planner for your 5,000 acres. Happy to walk through it when you have fifteen minutes.

Tyler Bramlett', 15000, 'sent', false, false, false, NULL, NULL, '2026-08-26T14:00:00Z', '2026-08-26T15:00:00Z', '2026-09-19T16:30:00Z'),
('OPP-0029', NULL, 'ACC-018', 'REP-03', 44, 'Irrigation Scheduling', 'List-based prospecting: Schmidt Bros. Farms was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Irrigation Scheduling for Schmidt Bros. Farms', 'Hi James,

Checking in on Irrigation Scheduling for your 2,200 acres. Happy to walk through it when you have fifteen minutes.

Marcus Deleon', 11300, 'sent', false, false, true, NULL, NULL, '2026-09-04T14:00:00Z', '2026-09-04T15:00:00Z', '2026-09-05T16:30:00Z'),
('OPP-0030', NULL, 'ACC-035', 'REP-06', 60, 'Irrigation Scheduling', 'List-based prospecting: Weber Grain Co. was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Irrigation Scheduling for Weber Grain Co.', 'Hi Sharon,

Checking in on Irrigation Scheduling for your 1,600 acres. Happy to walk through it when you have fifteen minutes.

Sofia Marchetti', 8900, 'sent', false, false, false, NULL, NULL, '2026-08-15T14:00:00Z', '2026-08-16T15:00:00Z', '2026-09-02T16:30:00Z'),
('OPP-0031', NULL, 'ACC-037', 'REP-05', 20, 'Irrigation Scheduling', 'List-based prospecting: Reimer Family Farm was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Irrigation Scheduling for Reimer Family Farm', 'Hi David,

Checking in on Irrigation Scheduling for your 6,500 acres. Happy to walk through it when you have fifteen minutes.

Tyler Bramlett', 28500, 'pushed', false, false, false, NULL, NULL, '2026-08-05T14:00:00Z', '2026-08-05T15:00:00Z', NULL),
('OPP-0032', NULL, 'ACC-038', 'REP-03', 10, 'Field-Work Planner', 'List-based prospecting: Yoder Land & Cattle Co. was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Field-Work Planner for Yoder Land & Cattle Co.', 'Hi Mary,

Checking in on Field-Work Planner for your 2,800 acres. Happy to walk through it when you have fifteen minutes.

Marcus Deleon', 9500, 'draft', false, false, false, NULL, NULL, '2026-08-27T14:00:00Z', NULL, NULL),
('OPP-0033', NULL, 'ACC-022', 'REP-01', 83, 'Field-Work Planner', 'List-based prospecting: Suderman Ranch was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Field-Work Planner for Suderman Ranch', 'Hi Linda,

Checking in on Field-Work Planner for your 800 acres. Happy to walk through it when you have fifteen minutes.

Jordan Ellsworth', 4500, 'sent', false, false, false, NULL, NULL, '2026-09-20T14:00:00Z', '2026-09-21T15:00:00Z', '2026-09-21T16:30:00Z'),
('OPP-0034', NULL, 'ACC-050', 'REP-06', 13, 'Field-Work Planner', 'List-based prospecting: Neufeld Ranch was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Field-Work Planner for Neufeld Ranch', 'Hi Linda,

Checking in on Field-Work Planner for your 3,500 acres. Happy to walk through it when you have fifteen minutes.

Sofia Marchetti', 11200, 'draft', false, false, false, NULL, NULL, '2026-08-24T14:00:00Z', NULL, NULL),
('OPP-0035', NULL, 'ACC-049', 'REP-05', 13, 'Field-Work Planner', 'List-based prospecting: Becker Ranch was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Field-Work Planner for Becker Ranch', 'Hi Ruth,

Checking in on Field-Work Planner for your 6,500 acres. Happy to walk through it when you have fifteen minutes.

Tyler Bramlett', 18800, 'draft', false, false, false, NULL, NULL, '2026-09-14T14:00:00Z', NULL, NULL),
('OPP-0036', NULL, 'ACC-041', 'REP-02', 11, 'Field-Work Planner', 'List-based prospecting: Becker Grain Co. was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Field-Work Planner for Becker Grain Co.', 'Hi Nancy,

Checking in on Field-Work Planner for your 6,500 acres. Happy to walk through it when you have fifteen minutes.

Priya Nathan', 18800, 'draft', false, false, false, NULL, NULL, '2026-09-17T14:00:00Z', NULL, NULL),
('OPP-0037', NULL, 'ACC-008', 'REP-05', 39, 'Irrigation Scheduling', 'List-based prospecting: Brandt Ranch was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Irrigation Scheduling for Brandt Ranch', 'Hi Donna,

Checking in on Irrigation Scheduling for your 4,200 acres. Happy to walk through it when you have fifteen minutes.

Tyler Bramlett', 19300, 'sent', false, false, false, NULL, NULL, '2026-08-27T14:00:00Z', '2026-08-27T15:00:00Z', '2026-09-26T16:30:00Z'),
('OPP-0038', NULL, 'ACC-013', 'REP-04', 61, 'Yield & Insurance Records', 'List-based prospecting: Bontrager Farming LLC was called as part of the quarterly territory sweep, not in response to a weather event.', 'FieldSense Yield & Insurance Records for Bontrager Farming LLC', 'Hi Donna,

Checking in on Yield & Insurance Records for your 1,600 acres. Happy to walk through it when you have fifteen minutes.

Renee Okafor', 4900, 'sent', false, false, false, NULL, NULL, '2026-09-01T14:00:00Z', '2026-09-01T19:00:00Z', '2026-09-02T02:00:00Z'),
('OPP-0039', 'SIG-0020', 'ACC-009', 'REP-04', 82, 'Irrigation Scheduling', 'Hartman Family Farm runs 1,600 acres of wheat in Cimarron County, which D3 to D4 this week; a watering plan pays for itself in the week allocations tighten.', 'Cimarron County just moved to exceptional drought — a watering plan for the acres you can still irrigate', 'Hi Sandra,

Cimarron County, OK drought category worsened to D4 (Exceptional Drought) this week (US Drought Monitor). With 1,600 acres of wheat, FieldSense Irrigation Scheduling can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Renee Okafor', 8900, 'sent', false, true, false, NULL, NULL, '2026-09-28T09:00:00Z', '2026-09-28T12:00:00Z', '2026-09-29T12:00:00Z'),
('OPP-0040', 'SIG-0020', 'ACC-021', 'REP-04', 73, 'Irrigation Scheduling', 'Sorensen Ag Partners runs 4,200 acres of corn in Cimarron County, which D3 to D4 this week; a watering plan pays for itself in the week allocations tighten.', 'Cimarron County just moved to exceptional drought — a watering plan for the acres you can still irrigate', 'Hi Sandra,

Cimarron County, OK drought category worsened to D4 (Exceptional Drought) this week (US Drought Monitor). With 4,200 acres of corn, FieldSense Irrigation Scheduling can tell you which fields matter most this week and keep the records straight if it turns into a claim.

Fifteen minutes Thursday?

Renee Okafor', 19300, 'pushed', false, true, false, NULL, NULL, '2026-09-28T09:00:00Z', '2026-09-28T14:00:00Z', NULL),
('OPP-0041', NULL, 'ACC-001', 'REP-05', 14, 'Irrigation Scheduling', 'List-based prospecting: Whitfield Land & Cattle Co. was called from a purchased list; no weather event in play.', 'FieldSense Irrigation Scheduling for Whitfield Land & Cattle Co.', 'Hi Mary,

Reaching out about FieldSense Irrigation Scheduling. Let me know if there is a good time to talk.

Tyler Bramlett', 11300, 'pushed', false, false, true, NULL, NULL, '2026-08-18T14:00:00Z', '2026-08-25T15:00:00Z', NULL),
('OPP-0042', NULL, 'ACC-003', 'REP-05', 15, 'Irrigation Scheduling', 'List-based prospecting: Neufeld Grain Co. was called from a purchased list; no weather event in play.', 'FieldSense Irrigation Scheduling for Neufeld Grain Co.', 'Hi Robert,

Reaching out about FieldSense Irrigation Scheduling. Let me know if there is a good time to talk.

Tyler Bramlett', 13700, 'pushed', false, false, true, NULL, NULL, '2026-08-18T14:00:00Z', '2026-08-25T15:00:00Z', NULL);

INSERT INTO settings (id, price_list) VALUES (1, '{"Irrigation Scheduling": 4.0, "Field-Work Planner": 2.5, "Yield & Insurance Records": 1.5, "setup": 2500}'::jsonb);
